---
# Template configuration files for compliance-roles

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ compliance-roles_templates_copy }}"
  when: compliance-roles_copy_templates
